<!doctype html>
<html lang="en">

<?php
include('templates/head.phtml') ?>

<body class="min-vh-100 d-flex flex-column">

<?php
include('templates/header.phtml') ?>

<!--@include('flash::message')-->

<main class="flex-grow-1">

    <!--    @yield('content')-->

    <div class="container-lg mt-3">
        <h1>Сайт: https://ru.wikipedia.org</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                <tr>
                    <td>ID</td>
                    <td>1</td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td>https://ru.wikipedia.org</td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td>2022-11-08 18:41:17</td>
                </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form method="post" action="/urls/1/checks">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover" data-test="checks">
            <tbody>
            <tr>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>Дата создания</th>
            </tr>
            <!--?php foreach ($checks as $check): ?-->

            </tbody>
        </table>
    </div>

</main>

<?php
include('templates/footer.phtml') ?>